export type ProfessionalExperienceType = {
  id?: number; // Optional because it will be autogenerated by Prisma
  title: string;
  company: string;
  startDate: Date;
  endDate: Date | "Present";
  description: string;
  createdAt?: Date; 
  updatedAt?: Date;
};
